---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: tektoncd-pipeline-enterprise-contract
spec:
  application: tektoncd-pipeline-release-v1.16.x
  contexts:
    - description: Application testing
      name: application
  params:
    - name: POLICY_CONFIGURATION
      value: rhtap-releng-tenant/registry-standard
  resolverRef:
    params:
      - name: url
        value: "https://github.com/konflux-ci/build-definitions"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git
