# TODO(#7325): use StepAction from Catalog
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: step-action-run-
spec:
  params:
    - name: pathInRepo
      value: basic_step.yaml
    - name: revision
      value: main
    - name: repoUrl
      value: https://github.com/chitrangpatel/repo1M.git
  TaskSpec:
    steps:
      - name: action-runner
        ref:
          resolver: git
          params:
            - name: url
              value: $(params.repoUrl)
            - name: revision
              value: $(params.revision)
            - name: pathInRepo
              value: $(params.pathInRepo)
