apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-pipelines/tektoncd-pipeline?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" &&
      ("upstream/***".pathChanged() || "openshift/patches/***".pathChanged() || "openshift/rpms/***".pathChanged() ||
      "openshift/dockerfiles/nop.Dockerfile".pathChanged() ||
      ".tekton/nop-pull-request.yaml".pathChanged() ||
      ".tekton/nop-push.yaml".pathChanged() ||
      ".tekton/docker-build.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tektoncd-pipeline-main
    appstudio.openshift.io/component: tektoncd-pipeline-main-nop
    pipelines.appstudio.openshift.io/type: build
  name: tektoncd-pipeline-main-nop-on-push
  namespace: tekton-ecosystem-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-main/nop:{{revision}}
  - name: dockerfile
    value: openshift/dockerfiles/nop.Dockerfile
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: |
      {"type": "rpm", "path": "openshift/rpms"}
  pipelineRef:
    name: docker-build
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
